name: Engine Build & Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:

  build:
    name: Build Engine Linux & Darwin
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    # Build Linux AMD64
    - name: Build Linux AMD64 CLI
      run: env GOOS=linux GOARCH=amd64 go build -o owl ./bin/cli.go

    - name: Build Linux AMD64 Server
      run: env GOOS=linux GOARCH=amd64 go build -o server ./main.go

    - name: Create Artefact Linux AMD64
      run: |
        mkdir -p engine-${{github.ref_name}}
        mv flows engine-${{github.ref_name}}/flows
        mv logs engine-${{github.ref_name}}/logs
        mv resources engine-${{github.ref_name}}/resources
        mv LICENSE engine-${{github.ref_name}}/LICENSE
        mv README.md engine-${{github.ref_name}}/README.md
        mv owl engine-${{github.ref_name}}/owl
        mv server engine-${{github.ref_name}}/server

    - uses: montudor/action-zip@v1
      with:
        args: zip -qq -r engine-linux-amd64-${{github.ref_name}}.zip engine-${{github.ref_name}}

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "engine-linux-amd64-${{github.ref_name}}"
        prerelease: false
        files: |
          engine-linux-amd64-${{github.ref_name}}.zip

    # Build Linux 386
    - name: Build Linux 386 CLI
      run: env GOOS=linux GOARCH=386 go build -o owl ./bin/cli.go

    - name: Build Linux 386 Server
      run: env GOOS=linux GOARCH=386 go build -o server ./main.go

    - name: Create Artefact Linux 386
      run: |
        mv owl engine-${{github.ref_name}}/owl
        mv server engine-${{github.ref_name}}/server

    - uses: montudor/action-zip@v1
      with:
        args: zip -qq -r engine-linux-386-${{github.ref_name}}.zip engine-${{github.ref_name}}

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "engine-linux-386-${{github.ref_name}}"
        prerelease: false
        files: |
          engine-linux-386-${{github.ref_name}}.zip

    # Build Darwin AMD64
    - name: Build Darwin AMD64 CLI
      run: env GOOS=darwin GOARCH=amd64 go build -o owl ./bin/cli.go

    - name: Build Darwin AMD64 Server
      run: env GOOS=darwin GOARCH=amd64 go build -o server ./main.go

    - name: Create Artefact Darwin AMD64
      run: |
        mv owl engine-${{github.ref_name}}/owl
        mv server engine-${{github.ref_name}}/server

    - uses: montudor/action-zip@v1
      with:
        args: zip -qq -r engine-darwin-amd64-${{github.ref_name}}.zip engine-${{github.ref_name}}

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "engine-darwin-amd64-${{github.ref_name}}"
        prerelease: false
        files: |
          engine-darwin-amd64-${{github.ref_name}}.zip
