name: Release Engine

on: [push]

jobs:

  build:
    name: Build Engine Linux & Darwin
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    # Build Linux
    - name: Build Linux AMD 64 CLI
      run: env GOOS=linux GOARCH=amd64 go build -o owl ./bin/cli.go

    - name: Build Linux AMD 64 Server
      run: env GOOS=linux GOARCH=amd64 go build -o server ./main.go

    - name: Create Artefact
      run: |
        mkdir -p engine-artifact
        mv flows engine-artifact/flows
        mv logs engine-artifact/logs
        mv resources engine-artifact/resources
        mv LICENSE engine-artifact/LICENSE
        mv README.md engine-artifact/README.md
        mv owl engine-artifact/owl
        mv server engine-artifact/server

    - uses: montudor/action-zip@v1
      with:
        args: zip -qq -r engine-linux-amd64.zip engine-artifact

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: false
        files: |
          engine-linux-amd64.zip

    # Build Darwin
    - name: Build Darwin AMD 64 CLI
      run: env GOOS=darwin GOARCH=amd64 go build -o owl ./bin/cli.go

    - name: Build Darwin AMD 64 Server
      run: env GOOS=darwin GOARCH=amd64 go build -o server ./main.go

    - name: Create Artefact
      run: |
        mv owl engine-artifact/owl
        mv server engine-artifact/server

    - uses: montudor/action-zip@v1
      with:
        args: zip -qq -r engine-darwin-amd64.zip engine-artifact

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: false
        files: |
          engine-darwin-amd64.zip
