name: Engine Build & Release

# on:
#   push:
#     tags:
#       - 'v*'

on: [push]

jobs:

  build:
    name: Build Engine for Linux & Darwin
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Create Artefact
      run: |
        mkdir -p artifact
        mv flows artifact/flows
        mv logs artifact/logs
        mv resources artifact/resources
        mv LICENSE artifact/LICENSE
        mv README.md artifact/README.md

    # Build Executable
    - name: Build Executable
      run: |
        sudo apt-get update
        sudo apt-get install -y libtesseract-dev libleptonica-dev tesseract-ocr-eng tesseract-ocr-ind
        env GOOS=linux GOARCH=amd64 go build -o artifact/owl-linux-amd64 ./bin/cli.go
        env GOOS=linux GOARCH=amd64 go build -o artifact/server-linux-amd64 ./main.go
        env GOOS=darwin GOARCH=amd64 go build -o artifact/owl-darwin-amd64 ./bin/cli.go
        env GOOS=darwin GOARCH=amd64 go build -o artifact/server-darwin-amd64 ./main.go
        env GOOS=windows GOARCH=amd64 go build -o artifact/owl-windows-amd64.exe ./bin/cli.go
        env GOOS=windows GOARCH=amd64 go build -o artifact/server-windows-amd64.exe ./main.go

    - uses: montudor/action-zip@v1
      with:
        args: zip -qq -r engine-${{github.ref_name}}.zip artifact

    - name: Release
      uses: anton-yurchenko/git-release@main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: |
            ./*.zip
